imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
parameters:
    exception_listener.controller: "StatsBundex:Exception:exception"
    
    
parameters:
    upload_dir: %kernel.root_dir%/../data/uploads/temp    