# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

StatsBankBundle:
    resource: "@StatsBankBundle/Resources/config/routing.yml"
    prefix: