services:
    stats_bank.service.account:
        class:  Stats\BankBundle\Service\AccountService
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@stats.service.upload", "@stats.component.parser", "@stats.accountValidator", "@stats.repository.accountStatement"]
    stats.service.upload:
        class:  Stats\BankBundle\Service\Uploader
        arguments: ["%upload_dir%"]
    
    stats.repository.accountStatement:
        class: Stats\BankBundle\Repository\AccountStatementRepository
        arguments: [Stats\BankBundle\Entity\AccountStatement]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        
    stats.component.parser:
        class:  Stats\Component\Csv\Parser
        arguments: ["\t"]
    stats.accountValidator:
        class: Stats\BankBundle\Component\Validator\AccountValidator
        arguments: ["@validator"]